/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
    export interface GlobalComponents {
        Icons: typeof import('./src/components/icons/index.vue')['default']
        RouterLink: typeof import('vue-router')['RouterLink']
        RouterView: typeof import('vue-router')['RouterView']
        SvgIcon: typeof import('./src/components/svg-icon/index.vue')['default']
    }
}
